### PR TITLE
More enhanced™️

### PR DESCRIPTION
**Pull request by tbeseda**
Instead of creating a static .css file in a user's ./public directory, hydrate that CSS file and provide a Lambda for serving it. Additionally, add a helper function to dynamically inline styles or create a <link> tag for that .css file.

See the HTML in the test route for new usage https://github.com/enhance-dev/arc-plugin-styles/blob/c3609e74200fe264c125518b6219dd973ae7ba33/test/mock/src/http/get-index/index.mjs

Some feedback implemented. We should release an RC and test in `arc-plugin-enhance`

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
I ran into two issues testing this plugin out locally.
1. There is an error due to a missing sandbox.start command
2. When running the app the plugin can't find the generated css file
> ENOENT: no such file or directory, open '.../node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/node_modules/@architect/shared/enhance-styles/generated.css'

**Comment by tbeseda** [comment]
Thanks for testing out @kristoferjoseph 

I wonder if **_(2)_** is caused by **_(1)_**. If the plugin balks then a .css file wouldn't be created in that destination

> > ENOENT: no such file or directory, open '.../node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/node_modules/@architect/shared/enhance-styles/generated.css'

**_(1)_** might be an issue with the Architect plugin API where it expects a `start()` method if `sandbox` is provided by the plugin. Since we're now using `hydrate.copy`, we don't need to do things on `sandbox|deploy.start`.

For now we may just be able to provide a no-op `sandbox.start`. This is easy to test locally. I can do that!  
Then we can look into investigating the potential Arc "bug" -- maybe it's intended? unsure.

**Comment by tbeseda** [comment]
Ah, no (2) was not caused by (1). Working on correct that.

**Comment by tbeseda** [comment]
Okay, whew. I released [an `arc-plugin-styles` RC](https://www.npmjs.com/package/@enhance/arc-plugin-styles/v/2.0.0-RC.1) from this branch.
I also released [an experimental `arc-plugin-enhance`](https://www.npmjs.com/package/@enhance/arc-plugin-enhance/v/0.0.0-experimental-56f71a8f95e014535b2fd85a370709863f0abf87) that consumes this RC
Then I made [a sample application](https://github.com/tbeseda/scratch-enhance-app-new-styles-plugin) that uses the experimental release of Enhance here

**Review by kristoferjoseph — APPROVED** [review]

**Pull request merged**
